// LenderMapping for mortgage search screens and should be imported like this:
// import { getLenderName, getLenderUrl, getLenderImage } from "@/lenderMapping.js";
// TODO add these utils to a class so we access them like LenderMapping.getLenderName
export function getLenderName(mbLenderId) {
  var name = lenderName[mbLenderId];
  //
  return name;
}

export function getLenderUrl(mbLenderId) {
  var url = lenderUrl[mbLenderId];
  //
  return url;
}

export function getLenderImage(mbLenderId) {
  var img = lenderImage[mbLenderId];
  //
  return img;
}

/* spell-checker: disable */
// TODO build these daily from MB and get from goLang cached API
const lenderName = {
  360: "Accord Mortgages",
  495: "Al Rayan Bank",
  595: "Aldermore Bank PLC",
  230: "Bank of China (UK)",
  628: "Bank of Ireland",
  115: "Barclays",
  190: "Bath Inv. + B.Soc.",
  1089: "Bespoke BOI",
  6: "Beverley",
  274: "Bluestone Mortgages",
  123: "BM Solutions",
  183: "Buckinghamshire BSoc",
  15: "Cambridge BS",
  17: "Chelsea B Society",
  297: "Chorley BS",
  163: "Clydesdale Bank PLC",
  1058: "Coutts Bank",
  28: "Coventry",
  37: "Coventry BS-Godiva",
  30: "Darlington",
  828: "Dudley B Society",
  187: "Earl Shilton B.Soc",
  48: "Ecology B.Soc",
  74: "Family Building Soc",
  711: "First Direct",
  796: "Fleet Mortgages",
  786: "Foundation HomeLoans",
  198: "Furness B.Soc",
  42: "Halifax",
  208: "Hanley Economic",
  45: "Harpenden",
  50: "Hinckley + Rugby BS",
  51: "Holmesdale B.Soc",
  154: "HSBC Direct",
  344: "HSBC Intermediary",
  53: "Ipswich",
  220: "Kensington",
  54: "Kent Reliance",
  57: "Leeds B Society",
  934: "Leeds Retention",
  803: "Leek United BS",
  142: "Lloyds Bank",
  61: "Loughborough B.S.",
  791: "Magellan Homeloans",
  63: "Mansfield",
  64: "Market Harborough",
  65: "Marsden",
  627: "MBS Lending Ltd",
  66: "Melton Mowbray",
  724: "Metro Bank Plc",
  71: "Monmouthshire",
  81: "N+P",
  75: "Nationwide B.Soc",
  619: "NatWest Direct",
  816: "NatWest Exclusive",
  207: "NatWest Intermediary",
  76: "Newbury",
  77: "Newcastle BS",
  82: "Nottingham",
  245: "Paragon Bank",
  937: "Paragon Residential",
  86: "Penrith",
  159: "Pepper Money",
  40: "Platform BTL",
  769: "Platform Mainstream",
  59: "Post Office Direct",
  351: "Precise Mortgages",
  90: "Principality",
  23: "Progressive B.Soc.",
  31: "RBS Direct",
  95: "Saffron B.Society",
  1: "Santander",
  156: "Scottish B.Soc",
  181: "Scottish Widows Bank",
  760: "Secure Trust Bank",
  140: "Skipton B.Society",
  189: "Stafford Railway BS",
  132: "Teachers B Society",
  503: "Tesco Bank",
  393: "The Mortgage Lender",
  168: "The Mortgage Works",
  105: "Tipton + Coseley",
  313: "TSB - Intermediaries",
  129: "TSB Direct",
  175: "Vernon BS",
  80: "Virgin Money PLC",
  560: "West Bromwich B. Soc",
  116: "Yorkshire B.Soc",
  259: "Yorkshire Bank",
  1048: "Zephyr Homeloans",
  267: "First Trust",
  661: "Danske Bank",
  613: "Postoffice"
};

const lenderUrl = {
  360: "www.accordmortgages.com",
  495: "www.alrayanbank.co.uk",
  595: "www.aldermore-mortgages.co.uk",
  230: "www.bankofchina.com/uk/pbservice/pb2/interm",
  628: "www.bankofirelanduk.com/mortgages/",
  115: "www.barclays.co.uk",
  190: "www.bibs.co.uk",
  1089: "www.bankofirelanduk.com/mortgages/",
  6: "www.beverleybs.co.uk",
  274: "www.bluestone.co.uk",
  123: "www.bmsolutions.co.uk",
  183: "www.bucksbuildingsociety.co.uk",
  15: "www.cambridgebs.co.uk",
  17: "www.thechelsea.co.uk/index.html",
  297: "www.chorleybs.co.uk",
  163: "www.clydesdalebankintermediaries.co.uk",
  1058: "www.coutts.com",
  28: "www.covconnect.co.uk",
  37: "www.covconnect.co.uk",
  30: "www.darlington.co.uk",
  828: "www.dudleybuildingsociety.co.uk/intermediary",
  187: "www.esbs.co.uk",
  48: "www.ecology.co.uk",
  74: "www.familybuildingsociety.co.uk",
  711: "www.firstdirect.com",
  796: "www.fleetmortgages.co.uk/",
  786: "www.foundationforintermediaries.co.uk/",
  198: "www.furnessbs.co.uk",
  42: "www.halifax-intermediaries.co.uk",
  208: "www.thehanley.co.uk/mortgages/",
  45: "www.harpendenbs.co.uk",
  50: "www.hrbs.co.uk",
  51: "www.holmesdale.org.uk",
  154: "www.hsbc.co.uk/mortgages/",
  344: "www.hsbc.co.uk/mortgages/",
  53: "www.ibs.co.uk/intermediaries/e-mortgage-services",
  220: "www.kmc.co.uk/intermediary.html",
  54: "www.krbs.com/products/mortgages/intermediaries",
  57: "www.leedsbuildingsociety.co.uk/introducers/",
  934: "www.leedsbuildingsociety.co.uk/introducers/",
  803: "www.leekunited.co.uk/intermediaries",
  142: "www.lloydsbank.com/mortgages.asp",
  61: "www.theloughborough.co.uk",
  791: "www.magellanhomeloans.co.uk/",
  63: "www.mansfieldbs.co.uk",
  64: "www.mhbs.co.uk",
  65: "www.themarsden.co.uk",
  627: "www.mbslending.co.uk",
  66: "www.themelton.co.uk",
  724: "www.metrobankonline.co.uk/mortgages/",
  71: "www.monbs.com/mortgages/",
  81: "www.npbs-intermediaries.co.uk",
  75: "www.nationwide-intermediary.co.uk/",
  619: "personal.natwest.com/personal/mortgages.html",
  816: "personal.natwest.com/personal/mortgages.html",
  207: "personal.natwest.com/personal/mortgages.html",
  76: "www.newbury.co.uk",
  77: "www.newcastleis.co.uk",
  82: "www.thenottingham-intermediaries.com",
  245: "www.paragonbank.co.uk",
  937: "www.paragonbank.co.uk",
  86: "www.penrithbs.co.uk",
  159: "www.peppergroup.co.uk/lending",
  40: "www.platform.co.uk",
  769: "www.platform.co.uk",
  59: "www.postoffice.co.uk/finance/mortgages",
  351: "www.precisemortgages.co.uk",
  90: "www.principality.co.uk/en/mortgages",
  23: "www.theprogessive.com",
  31: "personal.rbs.co.uk/personal.html",
  95: "www.saffronbs.co.uk",
  1: "www.santanderforintermediaries.co.uk",
  156: "www.scottishbs.co.uk/intermediary",
  181: "www.scottishwidows.co.uk/extranet",
  760: "www.securetrustbank.com/intermediaries",
  140: "www.skipton-intermediaries.co.uk",
  189: "www.srbs.co.uk",
  132: "www.teachersbs.co.uk",
  503: "www.tescobank.com/mortgages/",
  393: "www.themortgagelender.com/",
  168: "www.themortgageworks.co.uk",
  105: "www.thetipton.co.uk",
  313: "www2.tsb.co.uk/mortgages/",
  129: "www2.tsb.co.uk/mortgages/",
  175: "www.thevernon.co.uk",
  80: "www.virginmoneyforintermediaries.com",
  560: "www.westbrom.co.uk/mortgages",
  116: "www.ybs.co.uk",
  259: "secure.ybonline.co.uk/personal/mortgages/",
  1048: "zephyrhomeloans.co.uk/",
  267: "firsttrust.com/",
  661: "danskebank.co.uk/personal",
  613: "www.postoffice.co.uk/finance/mortgages"
};
/* spell-checker: enable */
const lenderImage = {
  360: "https://domun.co.uk/img/lender-logos/accordmortgages.png",
  495: "https://domun.co.uk/img/lender-logos/alrayanbank.png",
  595: "https://domun.co.uk/img/lender-logos/aldermorebank.png",
  230: "https://domun.co.uk/img/lender-logos/bankofchinauk.jpeg",
  628: "https://domun.co.uk/img/lender-logos/bankofireland.jpeg",
  115: "https://domun.co.uk/img/lender-logos/barclays.jpeg",
  190: "https://domun.co.uk/img/lender-logos/bathinv_and__bsoc.gif",
  1089: "https://domun.co.uk/img/lender-logos/bespokeboi.jpeg",
  6: "https://domun.co.uk/img/lender-logos/beverley.png",
  274: "https://domun.co.uk/img/lender-logos/bluestonemortgages.jpeg",
  123: "https://domun.co.uk/img/lender-logos/bmsolutions.jpeg",
  183: "https://domun.co.uk/img/lender-logos/buckinghamshire_bsococ.gif",
  15: "https://domun.co.uk/img/lender-logos/cambridge_bsoc.jpeg",
  17: "https://domun.co.uk/img/lender-logos/chelsea_bsoc.jpeg",
  297: "https://domun.co.uk/img/lender-logos/chorley_bsoc.png",
  163: "https://domun.co.uk/img/lender-logos/clydesdalebank.jpeg",
  1058: "https://domun.co.uk/img/lender-logos/couttsbank.jpeg",
  28: "https://domun.co.uk/img/lender-logos/coventry.jpeg",
  37: "https://domun.co.uk/img/lender-logos/coventry_bsocgodiva.jpeg",
  30: "https://domun.co.uk/img/lender-logos/darlington.jpeg",
  828: "https://domun.co.uk/img/lender-logos/dudley_bsoc.png",
  187: "https://domun.co.uk/img/lender-logos/earlshilton_bsoc.jpeg",
  48: "https://domun.co.uk/img/lender-logos/ecology_bsoc.jpeg",
  74: "https://domun.co.uk/img/lender-logos/family_bsoc.png",
  711: "https://domun.co.uk/img/lender-logos/firstdirect.jpeg",
  796: "https://domun.co.uk/img/lender-logos/fleetmortgages.png",
  786: "https://domun.co.uk/img/lender-logos/foundationhomeloans.png",
  198: "https://domun.co.uk/img/lender-logos/furness_bsoc.jpeg",
  42: "https://domun.co.uk/img/lender-logos/halifax.jpeg",
  208: "https://domun.co.uk/img/lender-logos/hanleyeconomic.png",
  45: "https://domun.co.uk/img/lender-logos/harpenden.jpeg",
  50: "https://domun.co.uk/img/lender-logos/hinckley_and_rugby_bsoc.png",
  51: "https://domun.co.uk/img/lender-logos/holmesdale_bsoc.jpeg",
  154: "https://domun.co.uk/img/lender-logos/hsbcdirect.png",
  344: "https://domun.co.uk/img/lender-logos/hsbcintermediary.png",
  53: "https://domun.co.uk/img/lender-logos/ipswich.jpeg",
  220: "https://domun.co.uk/img/lender-logos/kensington.png",
  54: "https://domun.co.uk/img/lender-logos/kentreliance.jpeg",
  57: "https://domun.co.uk/img/lender-logos/leedsretention.jpeg",
  934: "https://domun.co.uk/img/lender-logos/leeds_bsoc.jpeg",
  803: "https://domun.co.uk/img/lender-logos/leekunited_bsoc.jpeg",
  142: "https://domun.co.uk/img/lender-logos/lloydsbank.png",
  61: "https://domun.co.uk/img/lender-logos/loughborough_bsoc.gif",
  791: "https://domun.co.uk/img/lender-logos/magellanhomeloans.jpeg",
  63: "https://domun.co.uk/img/lender-logos/mansfield.gif",
  64: "https://domun.co.uk/img/lender-logos/marketharborough.jpeg",
  65: "https://domun.co.uk/img/lender-logos/marsden.jpeg",
  627: "https://domun.co.uk/img/lender-logos/mbslending.gif",
  66: "https://domun.co.uk/img/lender-logos/meltonmowbray.gif",
  724: "https://domun.co.uk/img/lender-logos/metrobank.png",
  71: "https://domun.co.uk/img/lender-logos/monmouthshire.jpeg",
  81: "https://domun.co.uk/img/lender-logos/nationwide_bsoc.png",
  75: "https://domun.co.uk/img/lender-logos/natwestdirect.jpeg",
  619: "https://domun.co.uk/img/lender-logos/natwestexclusive.jpeg",
  816: "https://domun.co.uk/img/lender-logos/natwestintermediary.jpeg",
  207: "https://domun.co.uk/img/lender-logos/newbury.png",
  76: "https://domun.co.uk/img/lender-logos/newcastle_bsoc.jpeg",
  77: "https://domun.co.uk/img/lender-logos/nottingham.jpeg",
  82: "https://domun.co.uk/img/lender-logos/n_and_p.jpeg",
  245: "https://domun.co.uk/img/lender-logos/paragonbank.jpeg",
  937: "https://domun.co.uk/img/lender-logos/paragonresidential.jpeg",
  86: "https://domun.co.uk/img/lender-logos/penrith.jpeg",
  159: "https://domun.co.uk/img/lender-logos/peppermoney.png",
  40: "https://domun.co.uk/img/lender-logos/platformbtl.jpeg",
  769: "https://domun.co.uk/img/lender-logos/platformmainstream.jpeg",
  59: "https://domun.co.uk/img/lender-logos/postofficedirect.gif",
  351: "https://domun.co.uk/img/lender-logos/precisemortgages.png",
  90: "https://domun.co.uk/img/lender-logos/principality.jpeg",
  23: "https://domun.co.uk/img/lender-logos/progressive_bsoc.png",
  31: "https://domun.co.uk/img/lender-logos/rbsdirect.png",
  95: "https://domun.co.uk/img/lender-logos/saffron_bsoc.gif",
  1: "https://domun.co.uk/img/lender-logos/santander.jpeg",
  156: "https://domun.co.uk/img/lender-logos/scottishwidowsbank.jpeg",
  181: "https://domun.co.uk/img/lender-logos/scottish_bsoc.jpeg",
  760: "https://domun.co.uk/img/lender-logos/securetrustbank.jpeg",
  140: "https://domun.co.uk/img/lender-logos/skipton_bsoc.png",
  189: "https://domun.co.uk/img/lender-logos/staffordrailway_bsoc.gif",
  132: "https://domun.co.uk/img/lender-logos/teachers_bsoc.jpeg",
  503: "https://domun.co.uk/img/lender-logos/tescobank.jpeg",
  393: "https://domun.co.uk/img/lender-logos/themortgagelender.png",
  168: "https://domun.co.uk/img/lender-logos/themortgageworks.png",
  105: "https://domun.co.uk/img/lender-logos/tipton_and_coseley.jpeg",
  313: "https://domun.co.uk/img/lender-logos/tsbdirect.jpeg",
  129: "https://domun.co.uk/img/lender-logos/tsbintermediaries.jpeg",
  175: "https://domun.co.uk/img/lender-logos/vernon_bsoc.jpeg",
  80: "https://domun.co.uk/img/lender-logos/virginmoney.png",
  560: "https://domun.co.uk/img/lender-logos/westbromwich_bsoc.gif",
  116: "https://domun.co.uk/img/lender-logos/yorkshirebank.gif",
  259: "https://domun.co.uk/img/lender-logos/yorkshire_bsoc.gif",
  1048: "https://domun.co.uk/img/lender-logos/zephyrhomeloans.png",
  267: "https://domun.co.uk/img/lender-logos/firsttrust.png",
  661: "#",
  613: "https://domun.co.uk/img/lender-logos/postofficedirect.gif"
};
